# Generated by Django 2.0.dev20170813003239 on 2018-01-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20171227_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='news.Author'),
        ),
    ]
