# Generated by Django 2.0.dev20170813003239 on 2018-04-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180331_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
