# Generated by Django 2.0.dev20170813003239 on 2018-04-06 18:40

from django.db import migrations
from django.conf import settings

def add_profiles_for_users(apps, schema_editor):
    Profile = apps.get_model("core", "Profile")
    User = apps.get_model("auth", "User")
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_profiles_for_users),
    ]
