# Generated by Django 2.0.dev20170813003239 on 2017-09-15 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoty_name', models.CharField(max_length=200)),
                ('categoty_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=200)),
                ('added_date', models.DateTimeField(verbose_name='pub date')),
                ('price', models.FloatField()),
                ('count', models.IntegerField()),
                ('color', models.TextField(choices=[('GR', 'green'), ('BL', 'blue'), ('WT', 'white'), ('BL', 'black')])),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopRecycle.Category')),
            ],
        ),
    ]
