# Generated by Django 2.0.dev20170813003239 on 2017-09-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopRecycle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoty_description',
            new_name='category_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoty_name',
            new_name='category_name',
        ),
    ]
