# Generated by Django 2.0.dev20170813003239 on 2018-04-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopRecycle', '0003_auto_20180121_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='should_be_on_main',
            field=models.BooleanField(default=False),
        ),
    ]
